### PR TITLE
Agricraft 1.4.6 initial commit

### PR DESCRIPTION
**Pull request by dragagon**
Getting into FTB Infinity Evolved and Expert mode and creating guides for the 2.4.1 release. Started with the 1.4.6-hotfix build of Agricraft. It is "missing" the Crop Mutation image because its a right click placement on Crop Sticks and doesn't actually have an NEI listing. Created it to stay consistent with the GUI.

### CODE REVIEW

**Comment by andrewminer** [comment]
Wow, thanks dragagon!  I've just recently gotten into Agricraft myself and was thinking about getting started on this one.  Sorry it's been so long... I've been busy trying to get a entirely new version of the website out, and I wanted to introduce this along with it.  It's taking a bit longer than I would have liked.  :cry: 

If I can't get it done by this weekend, I'll at least put this up on the old site.  Thanks again for the hard work!

**Comment by dragagon** [comment]
Awesome. Sadly this is just agricraft and doesn't include Pam's
harvestcraft recipes, that'll be done soon with a "mod" for agricraft that
includes those recipes.

I got permission to do immersive engineering so I'm slowly working on the
multiblocks for that.

Also that reminds me, do you have any plans for expert mode infinity
evolved? I was thinking about making a "mod" that had all the expert
recipes in it as a hack, specifically because I'm waiting for the skyblock
pack they are testing.

**Comment by andrewminer** [comment]
You read my mind!  I literally just put together a mod pack where the main Tech Mod is Immersive Engineering, with the combination of Agricraft/Harvestcraft/Spice of Life for the agriculture side.

The plan for Agricraft/Harvestcraft as a separate "mod" sounds good.  It really doesn't fit in either one by itself, and the combination is certainly large enough to warrant a mod all of its own.

For the expert mode stuff, I'd recommend you take a look at the [`onlyif` directive](https://github.com/andrewminer/crafting-guide/wiki/Mod-Version-Data-Format) for the mod version format.  Using that, you could create an (empty) FTB Infinity Expert Mode mod and then mark certain recipes to only appear if that mod is present.  Likewise, you can disable other recipes using the inverse condition.  Then, all the end-user has to do to enable "expert mode" is activate that mod on the site, and all the recipes will change.

**Comment by dragagon** [comment]
Oh awesome. I'll be working on that in my spare time as I love the site but kinda sad to see less people adding to it because its 1) easy to do and 2) stuff is outdated quickly without help.

**Comment by dragagon** [comment]
One last thing, since this seems to be the easiest way to reach you...

Is there a way i can do Avarita's crafting recipes As in, a 9x9 crafting recipe? or am i hoping for too much?

**Comment by andrewminer** [comment]
All set, and thanks for the contribution!  I managed to create a nice graphic for the Crop Mutation (renamed to Cross Crops to match the Agricraft documentation), and cleaned up the recipe so that it accurately reflects the materials needed to make it in the crafting plan.  You should find it up on the website next time you check.  Thanks again!

**Pull request closed without merging**
