### PR TITLE
Logistics Pipes support

### PR DESCRIPTION
**Pull request by invalidCards**
- [x] Item Pipes
- [x] Fluid Pipes
- [x] Modules
- [x] Upgrades
- [x] Blocks
- [x] Items
- [x] Finishing up

Closes [crafting-guide#205](https://github.com/andrewminer/crafting-guide/issues/205)

### CODE REVIEW

**Comment by invalidCards** [comment]
Should be good to go.

**Comment by invalidCards** [comment]
@andrewminer onlyif is not valid syntax? Or did I miss something?

**Comment by andrewminer** [comment]
You missed the capital `i`.  You should use `onlyIf`.

**Comment by andrewminer** [comment]
All set!  Thanks for putting this together... it's been one of the more requested mods for a long while now!

**Pull request merged**
