### PR TITLE
Added IDT Mod

### PR DESCRIPTION
**Pull request by Nulcheck**
It's updated to 15w18a mod snapshot, and crafting stuff has been fixed.

### CODE REVIEW

**Comment by andrewminer** [comment]
It looks like the tests don't pass.  :grimacing:  Even after matching up the `version` field in the `mod.cg` with the actual version (it should be: `version: 15w18a`), I get a bunch of test failures:

```
[redwood-labs-macbook:/src/crafting-guide-data]$ grunt test
Running "mochaTest:src" (mochaTest) task


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․

  26 passing (56ms)
  1 failing

  1) data files for idt 15w18a loads mod-version.cg without errors:

      AssertionError: expected [ Array(13) ] to deeply equal []
      + expected - actual

      +[]
      -[
      -  "Error: line 7: Unknown command: pattern .0. ... .1."
      -  "Error: line 19: Unknown command: exrtas"
      -  "Error: line 55: a pattern must have 9 digits using 0-9 for items and \".\" for an empty spot; spaces are optional"
      -  "Error: line 99: a pattern must have 9 digits using 0-9 for items and \".\" for an empty spot; spaces are optional"
      -  "Error: line 164: Unknown command: pattern .0. .1. ..."
      -  "Error: line 266: Unknown command: Item"
      -  "Error: line 610: a pattern must have 9 digits using 0-9 for items and \".\" for an empty spot; spaces are optional"
      -  "Error: line 5: the \"pattern\" declaration is required"
      -  "Error: line 53: the \"pattern\" declaration is required"
      -  "Error: line 97: the \"pattern\" declaration is required"
      -  "Error: line 162: the \"pattern\" declaration is required"
      -  "Error: line 507: duplicate recipe: idt__hard_crystal_ball,spruce_sapling>>idt__essence_of_life"
      -  "Error: line 608: the \"pattern\" declaration is required"
      -]

    at Context.<anonymous> (test/data.test.coffee:44:64)




Warning: Task "mochaTest:src" failed. Use --force to continue.

Aborted due to warnings.
```

Can you clean up those test errors and push up a new commit on this branch?  Thanks!

**Comment by andrewminer** [comment]
Also, please clean up the `Thumbs.db` files all over the place.  Thanks!

**Comment by andrewminer** [comment]
I'm doing a little spot-checking of the individual item descriptions, and they appear to have some quality issues as well.  For example, the "Birch Fence" item has a description of "Colored wooden wall!".  It's best to omit descriptions where they don't really add anything which isn't already apparent.  Don't feel like you're obliged to fill in _everything_ just because it's there.

Another example of the same sort of thing came up with "Einsteinium Ore".  Here you describe a feature and the say "not implemented yet".  It's best to keep descriptions to what actually is in the mod right now, and to omit things which have been removed or not yet added.

Another change which I recently released on the site is to update the syntax of internal links to use the GitHub-style wiki links.  So, when referring to other items, you need to use `[[...]]` instead of single brackets.

**Comment by andrewminer** [comment]
Another example is the description for "Empty Tank".  This description also fails to provide any information beyond what is implied by the name.  In this case, unlike with the "Birch Fence", I expect there's something else to know. What's the tank's capacity? What can it hold?  What means are available to fill it up and empty it? Can it be secured from use by other players? Does it keep its contents when picked up?  A really great description will anticipate what a player will need to know about and item and try to provide all those details.

**Comment by andrewminer** [comment]
For the "IDT Crafting Table" and any other items which aren't implemented yet, it's probably best to omit them for now.  Once they're really working, it would be great to add them.

**Comment by Nulcheck** [comment]
Thumbs.db? i don't see those, even when i enable to show hidden items or when i search..

Edit: ok i see some in my Github dekstop app.

**Comment by andrewminer** [comment]
Well... just check the list of files in the commit.  There are a bunch of them.  The easiest way is probably to use the "Files Changed" tab at the top of this page.

edit: Just noticed your edit.  :smile: I do still see a bunch in the commit, though.  You'll need to remove them manually once they've been added.  The `.gitignore` file only helps with future actions using Git... not with things you've already committed.

**Comment by Nulcheck** [comment]
ok i went through all of them, i think it got all the thumbs.db
I also noticed some images weren't named icon.png, so i renamed them

**Comment by andrewminer** [comment]
Sorry I'm taking so long to get back to this... I've been working on a big new feature which is nearly complete, and I'll be able to check this out then.  Probably another day or two.  Thanks for your patience!

**Comment by Nulcheck** [comment]
no problem

**Comment by Nulcheck** [comment]
I recently updated my mod to a new snapshot, i'll be updating this as well within the next few days

**Comment by andrewminer** [comment]
Sounds good.  I've just gotten back from vacation, so I should have some time to check things out again in the next few days.  Just let me know when you're ready for me to look again.

**Comment by Nulcheck** [comment]
I'm moving to California in a month, i'll be busy doing mod and games stuff, hopefully i can get this updated before i leave

**Comment by Nulcheck** [comment]
ok i update it now

**Comment by Jacewayland2015** [comment]
Ok thanks for the help

**Comment by Nulcheck** [comment]
Had a small snapshot, just some armor and a few tools added, but i updated this as well. and deleted those thumbs.db files.

**Comment by Jacewayland2015** [comment]
Ok well just let me know if i can help you with anything k.

**Comment by andrewminer** [comment]
@MCE626—Sorry for the long delay!  I just finished getting the big new feature I've been working on released (image uploads while wiki editing!), and I was able to take a look at your pull request.

Unfortunately, I still see a number of problems:
1. There is a test failure.  Unfortunately the error message is not very helpful, but I looked into it, and you just need to either omit the `documentationUrl` in the `mod.cg` file or provide a proper link.
2. There are a number of items which are missing icons (e.g., Stone Bricks, Stone Button, Stone Slab, Super Reactor)
3. There are a number of places in the item descriptions where your wiki links aren't working properly (e.g., Chisel).  Make sure to use exact spelling and capitalization.  If there's an exact match, it will turn into a hyperlink.  If not, then you'll see `[[item name]]`.
4. There are a lot of weapons and armor which don't have any kind of description: just the fact that they are made of various kinds of metal using the standard recipes.  It would be super helpful if you included a tutorial page or at least some item descriptions helping users understand how these compare to the regular weapon & armor types.
5. The various reactors (e.g., Uranium Core Reactor) don't have descriptions, and it's really hard to infer much about them.  What kind of power do they produce? What sort of fuel do they use?  Do they require some kind of coolant? Can they become dangerous if mis-used?
6. There are at least a few items which seem unobtainable (e.g., liquid Nitrogen).  The descriptions in those cases really should specify where to get them, and how they can be used (i.e., can you use Nitrogen to cool reactors?)

I'm sorry to be so picky, but I think we'll both benefit from it.  There are certain things I think are absolutely necessary for the site not to appear broken (e.g., no missing icons), and other things I think are necessary for people to use and appreciate your mod.

I'd highly recommend you get the website running on your machine so you can browse the site for yourself and find all these little issues.  As you've noticed, I don't have a great deal of time to spent helping you catch these kind of problems, and I'm afraid waiting on my feedback is slowing you down.  :frowning:

**Comment by Nulcheck** [comment]
I've tried the local thing and looked at the tutorial many times, have all the programs you say, but i can't get it to work

Edit: It's saying "sudo" is not a git command..

**Comment by andrewminer** [comment]
You don't need to use "sudo" on Windows.  Sorry... the instructions were written with Mac/Linux in mind.

**Comment by Nulcheck** [comment]
Ah, got it.
well now it's error-ing at the grunt clean build part.. "Task "clean" not found."

**Comment by andrewminer** [comment]
I'd have to guess that you're not in the correct directory or that you don't have Grunt installed properly.

**Comment by Jacewayland2015** [comment]
Ok, thanks I don't know much about that mod but I will do some research
later on. K.

**Comment by Nulcheck** [comment]
Well i'm not sure what i'm doing wrong, my github shell window thing looks like this http://gyazo.com/066b4dce2b979dbdff895c956985a7b7

**Comment by andrewminer** [comment]
You don't need the "clean" and "build" commands for the data repository... just "test".  In the "crafting-guide" repository you'll want the "clean" and "build".  Sorry... I haven't gotten to updating the documentation yet since I split things into multiple projects.

**Comment by Nulcheck** [comment]
oh man this, totally forgot about it. been very busy with stuff. I'm not sure if i have the time to update it right now. i remember trying something with the github desktop app and something didn't work, i don't remember anymore.
Well i might update this sometime, i don't know when that'll be.

**Comment by andrewminer** [comment]
Hello @MCE626!  I'm going to close this pull request, but feel free to re-submit if you find you have time to work on it!

**Pull request closed without merging**
