### PR TITLE
add Draconic Evolution multiblocks

### PR DESCRIPTION
**Pull request by coehlrich**
This adds the Draconic Evolution Energy Storage tiers, the Draconic Reactor and the Draconic Resurrection Ritual.

### CODE REVIEW

**Comment by andrewminer** [comment]
I'm not sure how I missed this!  The code looks good.  Can you post the results of running the data tests?

**Comment by andrewminer** [comment]
I've downloaded this and checked it out, and things seem to work fine except:

1. The recipes are so wide that the break the website's layout!
2. None of the new multi-block items have images.

As for the first problem, I'm really no sure how best to deal with it, to be honest.  They really are just much too big to fit.  I'll have to think about what to do about that.  If you happen to know CSS and would like to give it a shot, you're more than welcome to do so.

As for the second problem, I've done this mostly by taking a screen-shot of the completed item from the renderer on this website and shrinking it down to a 48x48 png and adding it in the appropriate item directory.   I'd recommend you do the same, and then I'll merge this change in regardless of whether I've worked out how to deal with the website formatting.

**Comment by coehlrich** [comment]
When I was making it I was working on a pull request for the crafting guide exporter also I will add the item images tomorrow (in my time zone which is NZDT)

**Comment by coehlrich** [comment]
the render on the website wouldn't really work well for these multi blocks.

**Comment by coehlrich** [comment]
icon
this is currently what i have managed to do using https://gist.github.com/coehlrich/160bb45bc289070e50253344b1dde32d but when i replace blockX with x and blockZ with z and remove the * 16 for both it doesn't draw anything

**Comment by coehlrich** [comment]
I used the main blocks that are in the multiblock since it is kind of hard to get a render of it since the render on the website wouldn't really work well.

**Comment by andrewminer** [comment]
Close enough!  I agree that you won't even be able to tell what you're looking at if you just shrunk the whole thing down.  Merged and deployed!  Thanks very much for the help!

**Pull request merged**
